### ISSUE TITLE
Belt does not connect properly to one of the splitter types

### ISSUE THREAD

**Issue by Spirevipp** [KingEnderBrine/-DSP-SplitterOverConveyor#2]
When using your mod to place the splitter on top of a belt, it does not connect properly.
This is using the 2 low two high perpendicular splitter.
UI says the belt is connected to the top input?
See pictures.

Mods i use:
(this mod)
Advanced build destruct
CopyInserters
free foundations free soil

im on the DSP modding discord if you need help to reproduce etc, same username.

![20210223194118_1](https://user-images.githubusercontent.com/20364170/108892150-d67c7600-760f-11eb-90a8-3d164aba9ad9.jpg)

![20210223194123_1](https://user-images.githubusercontent.com/20364170/108892176-dda38400-760f-11eb-8e61-683801218493.jpg)

![20210223195406_1](https://user-images.githubusercontent.com/20364170/108893121-011afe80-7611-11eb-8e84-1fe16610d36a.jpg)

(edit: added one more photo showing the direction indicated by UI is occupied)

**Comment by KingEnderBrine** [comment]
Didn't know there were different splitter types. There are definitely some errors in slot detection (I've experienced myself with default splitters). I will work on it.

**Comment by KingEnderBrine** [comment]
Took a while. Published an update, that should fix these issues.
