### ISSUE TITLE
0.6.17.5932 Method not found: NearColliderLogic

### ISSUE THREAD

**Issue by Nielwulf** [KingEnderBrine/-DSP-SplitterOverConveyor#4]
![image](https://user-images.githubusercontent.com/6455774/110951593-de742f80-830a-11eb-9e78-5842caa122a3.png)
 After the most recent patch I am hit with this error when attempting to place a splitter. The message comes up immediately after selecting a splitter for construction.

**Comment by KingEnderBrine** [comment]
Published an update with fix
