### ISSUE TITLE
Splitters set with mod prevent mass belt upgrade to detect one belt section in splitter housing

### ISSUE THREAD

**Issue by Louis-Cyphre** [KingEnderBrine/-DSP-SplitterOverConveyor#5]
On the output side of the splitter, the mass upgrade function will not detect the innermost belt in the housing.
This only happens with splitters set on top of existing belts with this mod.
You can still update the single belt by peeking into the housing from a low angle and update it explicitly.

See the images: 
The left splitter is set before attaching the belts, the right one is built on top of existing belt.

![standard_set_splitter](https://user-images.githubusercontent.com/8995585/111283651-a25d0980-863f-11eb-9659-1693d9808af9.jpg)
![mod_set_splitter](https://user-images.githubusercontent.com/8995585/111283647-a1c47300-863f-11eb-8fcd-7136add394a5.jpg)

Kind regards,
Ingo

**Comment by KingEnderBrine** [comment]
Thanks for the report, I will take a look

**Comment by KingEnderBrine** [comment]
Published an update. This, sadly, doesn't affect already placed belts but placing new splitters shouldn't have that issue.

**Comment by Louis-Cyphre** [comment]
Awesome. Thanks for the fix ( and the neat mod of course )
